/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AnalysisProcessor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AnalysisResults": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Frontend": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "VideoAnalysisApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "VideoBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "VideoNotifications": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "VideoProcessor": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}